services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      SERVER_NAME: ':3000'
      MERCURE_PUBLISHER_JWT_KEY: 'BZ-eM4osfnEF7dgMMnFoJezKw1762vyksfKrnkaN6q-h3bDuBw6spPJGiaG8dAZncnlEelWnUw4JlRGSU3qbHw'
      MERCURE_SUBSCRIBER_JWT_KEY: 'BZ-eM4osfnEF7dgMMnFoJezKw1762vyksfKrnkaN6q-h3bDuBw6spPJGiaG8dAZncnlEelWnUw4JlRGSU3qbHw'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:5173 http://localhost:3000
      ports:
        - "3000:3000"
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config


      #docker compose -f docker-compose.mercure.yaml up -d